CREATE SCHEMA App
GO
CREATE TABLE App.Store
(
    StoreId SMALLINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Name VARCHAR(128) NOT NULL
);
CREATE UNIQUE INDEX uix_StoreName ON App.Store ([Name]);
GO
CREATE TABLE App.List
(
    ListId BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Name Varchar(128) NOT NULL,
    StoreId SMALLINT NULL FOREIGN KEY REFERENCES App.Store(StoreId),
    Archived BIT NOT NULL DEFAULT(0)
);
CREATE UNIQUE INDEX uix_ListName ON App.List ([Name]);
GO
CREATE TABLE App.Item
(
    ItemId BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Name VARCHAR(128) NOT NULL
);
CREATE UNIQUE INDEX ix_ItemName ON App.Item ([Name]);
GO

CREATE TABLE App.ListItem
(
    ListItemId BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ListId BIGINT NOT NULL FOREIGN KEY REFERENCES App.List(ListId),
    ItemId BIGINT NULL FOREIGN KEY REFERENCES App.Item(ItemId),
    Name VARCHAR(128),
    Quantity SMALLINT NOT NULL DEFAULT(1),
    Checked BIT NOT NULL DEFAULT(0),
    Username VARCHAR(64),
    ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    ValidTo DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    CHECK (Quantity>=0),
    PERIOD FOR SYSTEM_TIME(ValidFrom, ValidTo)
) WITH(SYSTEM_VERSIONING = ON(HISTORY_TABLE=App.ListItemHistory));
CREATE INDEX ix_ListItem_List on App.ListItem (ListId);
GO
CREATE UNIQUE INDEX uq_ListItem_Items ON App.ListItem(ListId, ItemId) WHERE ItemID IS NOT NULL;
GO
CREATE UNIQUE INDEX uq_ListItem_ItemName ON App.ListItem(ListId, [Name]) WHERE [Name] IS NOT NULL;
GO
CREATE TABLE App.StoreOrder
(
    StoreOrderID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    StoreId SMALLINT NOT NULL FOREIGN KEY REFERENCES App.Store(StoreId),
    ItemId BIGINT NOT NULL FOREIGN KEY REFERENCES App.Item(ItemId),
    [Order] INT NOT NULL DEFAULT(0)
);
CREATE UNIQUE INDEX uix_StoreOrder ON App.StoreOrder (StoreId, ItemId) INCLUDE ([Order]);
GO